try {
    hello()
} catch (error) {
    console.log(error)
}

try {
    anotherfn()
} catch {
    console.log('esto es un error')
}